export const s = {
  page: {
    minHeight: "100vh",
    background: "#09090B",
    backgroundImage: `
      radial-gradient(circle at 15% 20%, rgba(124,58,237,.18), transparent 30%),
      radial-gradient(circle at 85% 80%, rgba(59,130,246,.12), transparent 30%)
    `,
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "center",
    padding: "32px 16px",
  },
  layout: {
    display: "flex",
    gap: "20px",
    width: "100%",
    maxWidth: "1060px",
    alignItems: "flex-start",
    flexWrap: "wrap",
  },

  /* main card */
  card: {
    flex: 1,
    minWidth: 300,
    background: "#111113",
    border: "1px solid #232326",
    borderRadius: "28px",
    padding: "36px",
    boxShadow: "0 30px 80px rgba(0,0,0,.45)",
  },
  topRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 22,
    flexWrap: "wrap",
    gap: 10,
  },
  badge: {
    background: "rgba(199,146,234,0.12)",
    border: "1px solid rgba(199,146,234,0.3)",
    borderRadius: 8,
    padding: "6px 12px",
    fontSize: 12,
    fontWeight: 700,
    color: "#C792EA",
    fontFamily: "'Inter', sans-serif",
    letterSpacing: "0.5px",
  },
  badgeMono: {
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: 8,
    padding: "6px 12px",
    fontSize: 12,
    fontWeight: 600,
    color: "#6E6A8C",
    fontFamily: "'Inter', sans-serif",
  },
  timerWrap: {
    position: "relative",
    width: 64,
    height: 64,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  timerText: {
    position: "absolute",
    fontFamily: "'Inter', sans-serif",
    fontSize: 13,
    fontWeight: 700,
  },

  /* question card */
  qCard: {
    background: "#18181B",
    border: "1px solid #27272A",
    borderRadius: 18,
    padding: "20px 22px",
    marginBottom: 22,
  },
  qLabel: {
    fontFamily: "'Inter', sans-serif",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "2px",
    color: "#6E6A8C",
    marginBottom: 10,
  },
  qText: {
    fontFamily: "'Inter', sans-serif",
    fontSize: 17,
    fontWeight: 600,
    color: "#F4F4F5",
    lineHeight: 1.6,
  },

  /* transcript */
  transcriptLabel: {
    fontFamily: "'Inter', sans-serif",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "2px",
    color: "#6E6A8C", 
    marginBottom: 10,
  },
  transcriptBox: {
    background: "#0C0C0E",
    border: "1px solid #232326",
    borderRadius: 16,
    padding: "18px 20px",
    minHeight: 90,
    marginBottom: 22,
    fontFamily: "'Inter', sans-serif",
    fontSize: 14.5,
    lineHeight: 1.7,
    color: "#D4D4D8",
  },
  caret: {
    color: "#5ED1C9",
    animation: "blink 1s step-end infinite",
  },

  /* mic area */
  micArea: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 14,
    marginBottom: 24,
    padding: "10px 0 18px",
  },
  waveRow: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    height: 22,
  },
  micBtn: {
    width: 64,
    height: 64,
    borderRadius: "50%",
    border: "none",
    color: "#0A0A0C",
    fontSize: 22,
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "opacity .2s ease",
  },
  micStatus: {
    fontFamily: "'Inter', sans-serif",
    fontSize: 13,
    color: "#6E6A8C",
  },

  /* buttons */
  clearBtn: {
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: 14,
    padding: "16px 22px",
    color: "#A1A1AA",
    fontFamily: "'Inter', sans-serif",
    fontSize: 14,
    fontWeight: 600,
  },
  submitBtn: {
    background: "linear-gradient(135deg,#C792EA,#5ED1C9)",
    border: "none",
    borderRadius: 14,
    padding: "16px 22px",
    color: "#0A0A0C",
    fontFamily: "'Inter', sans-serif",
    fontSize: 14,
    fontWeight: 700,
    transition: "opacity .2s ease",
  },

  /* side panel */
  sidePanel: {
    width: 300,
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  faceBadge: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    border: "1px solid",
    borderRadius: 14,
    padding: "12px 16px",
    fontFamily: "'Inter', sans-serif",
    fontSize: 13,
    fontWeight: 600,
  },
  faceDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    flexShrink: 0,
  },
  videoWrap: {
    position: "relative",
    width: "100%",
    aspectRatio: "4 / 3",
    borderRadius: 18,
    overflow: "hidden",
    border: "1px solid #232326",
    background: "#000",
  },
  video: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    transform: "scaleX(-1)",
  },
  scanOverlay: {
    position: "absolute",
    inset: 0,
    pointerEvents: "none",
    background: "linear-gradient(180deg, transparent 0%, transparent 92%, rgba(94,209,201,0.08) 100%)",
  },

  /* scores */
  scoresBox: {
    background: "#111113",
    border: "1px solid #232326",
    borderRadius: 18,
    padding: "18px 20px",
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  scoreItem: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  scoreRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  scoreLabel: {
    fontFamily: "'Inter', sans-serif",
    fontSize: 12,
    fontWeight: 600,
    color: "#A1A1AA",
  },
  scoreVal: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 14,
    fontWeight: 700,
  },
  barTrack: {
    width: "100%",
    height: 6,
    borderRadius: 6,
    background: "rgba(255,255,255,0.06)",
    overflow: "hidden",
  },
  barFill: {
    height: "100%",
    borderRadius: 6,
    transition: "width .6s ease, background .3s ease",
  },
  warnCount: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },

  /* warning log */
  warnLog: {
    background: "#111113",
    border: "1px solid #232326",
    borderRadius: 18,
    padding: "16px 18px",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  warnLogTitle: {
    fontFamily: "'Inter', sans-serif",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "2px",
    color: "#6E6A8C",
    marginBottom: 4,
  },
  warnLogItem: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 11.5,
    color: "#FF8CC8",
    lineHeight: 1.6,
  },
}